name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

       - name: Compile Java files
      run: |
        mkdir -p classes
        javac -cp "libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar" -d classes $(find ./src -name "*.java") $(find ./test -name "*.java")
        
    - name: Run Tests
      run: |
        java -cp "classes:libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore LoginTest TaskTest

